stages:
  - test

image: registry.heptapod.host/pythonian/dockerizer/ci-image:latest

unit-test-job:
  stage: test
  tags:
    - clever-cloud
  script:
    - cd ..
    - hg clone https://heptapod.host/pythonian/timeseries-refinery/sqlhelp
    - hg -R sqlhelp update tip
    - pip install -e sqlhelp
    - hg clone https://heptapod.host/pythonian/timeseries-refinery/tshistory
    - hg -R tshistory update tip
    - pip install -e tshistory
    - hg clone https://heptapod.host/pythonian/timeseries-refinery/tshistory_supervision
    - hg -R tshistory_supervision update tip
    - pip install -e tshistory_supervision
    - hg clone https://heptapod.host/pythonian/timeseries-refinery/tshistory_formula
    - hg -R tshistory_formula update tip
    - pip install -e tshistory_formula
    - cd tshistory_xl
    - pip install -e .
    - ruff check .
    - pytest
